# ===========================================
# AlphaInsights — Phase Summary Generator
# ===========================================
# Usage:
#   .\tools\generate_phase_summary.ps1 "CVaR Optimizer Phase"
# Creates a new summary markdown file under /docs/progress_logs/
# ===========================================

param(
    [Parameter(Mandatory = $true)]
    [string]$PhaseName
)

# Prepare output filename with date
$today = Get-Date -Format "yyyy-MM-dd"
$outputDir = "docs\progress_logs"
$outputFile = "$outputDir\$today`_phase_summary.md"

# Collect recent commits (last 10 by default)
$commits = git log -n 10 --pretty=format:"- %s"

# Header for summary document
$content = @"
# AlphaInsights — Phase Summary: $PhaseName
**Date:** $today  
**Branch:** analytics-module  

---

## 🧾 Overview
Automatic phase summary generated via PowerShell utility.

---

## 🧠 Recent Commits
$commits

---

## 🧩 Next Steps
- Review new documentation and update `context_tracker.json` if version bump needed.  
- Ensure all new features or analytics are covered in corresponding knowledge capsules.  
- Run integrity check to verify folder structure remains intact.  

---

**Generated by:** tools/generate_phase_summary.ps1  
"@

# Ensure directory exists
if (!(Test-Path $outputDir)) {
    New-Item -ItemType Directory -Path $outputDir | Out-Null
}

# ✅ Write the content using .NET UTF-8 with BOM encoding (cross-version safe)
$utf8BOM = New-Object System.Text.UTF8Encoding $true
[System.IO.File]::WriteAllText($outputFile, $content, $utf8BOM)

Write-Host "`n✅ Phase summary created successfully:`n" -ForegroundColor Green
Write-Host $outputFile -ForegroundColor Cyan
